version: "3"

services:
  vlc:
    working_dir: /
    build:
      context: .
      dockerfile: Dockerfile-vlc
  app:
    build:
      context: .
    volumes:
      - c:\Users\binarycleric\Music\Collection\FLAC:/uploads:ro
    working_dir: /app
    command: "volcanofm"