version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\Users\binarycleric\Music\Collection\FLAC:/music
      - c:\Users\binarycleric\Code\go\src:/go/src
    working_dir: /app
    command: "volcanofm"