version: "3"

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - c:\Data\Projects\volcanofm\postgresql:/var/lib/postgresql/data:rw
  vlc:
    build:
      context: .
      dockerfile: Dockerfile-vlc
    ports:
      - 8080:8080
      - 4242:4242
    volumes:
      - c:\Data\Projects\volcanofm\data:/data:ro
  app:
    build: .
    links:
      # - db
      - vlc
    volumes:
      - c:\Users\binarycleric\Music\Collection\FLAC:/uploads:ro
      - c:\Data\Projects\volcanofm\data:/data:rw
    working_dir: /app
    command: "volcanofm"