FROM ubuntu:zesty

RUN apt-get update
RUN apt-get install vlc -y
RUN useradd -ms /bin/bash vlc

VOLUME ["/data"]

USER "vlc"

EXPOSE 4242
EXPOSE 8080

ENTRYPOINT ["/usr/bin/vlc"]
CMD ["-I", "oldrc", "--rc-fake-tty", "--rc-host=0.0.0.0:4242", "-vvv", "--sout", "#transcode{vcodec=none,acodec=vorb,ab=256,channels=2,samplerate=44100}:http{mux=ogg,dst=:8080/}", "--sout-keep"]